# Generated by Django 4.2.4 on 2023-09-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_posttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='commentUser',
            new_name='feedbackUser',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='commentPost',
        ),
        migrations.CreateModel(
            name='FeedBackMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('respondentThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.feedback')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='respondent',
            field=models.ManyToManyField(through='posts.FeedBackMany', to='posts.feedback'),
        ),
    ]
