# Generated by Django 4.2.4 on 2023-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_commentuser_feedback_feedbackuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='acception',
            field=models.BooleanField(default=False),
        ),
    ]
